# Generated by Django 5.2.3 on 2025-06-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_own_community',
            field=models.BooleanField(default=False),
        ),
    ]
