# Generated by Django 5.2.3 on 2025-06-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        ('event', '0006_alter_event_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='events', to='event.event'),
        ),
    ]
