# Generated by Django 5.2.3 on 2025-06-29 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_community_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='events',
        ),
    ]
