# Generated by Django 5.2.3 on 2025-06-26 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        ('event', '0002_event_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_list', to='community.community'),
        ),
    ]
