# Generated by Django 5.2.3 on 2025-06-26 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        ('event', '0005_auto_20250626_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_list', to='community.community'),
        ),
    ]
