# Generated by Django 5.2.3 on 2025-06-29 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_community_events'),
        ('event', '0006_alter_event_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_events', to='community.community'),
        ),
    ]
